---
- name: debian | running apt-get update
  apt:
    update_cache: yes
    cache_valid_time: 86400
  tags:
    - apt_update
  become: true

- name: debian | running apt-get update (forced)
  apt:
    update_cache: yes
  tags:
    - force-apt-update
  become: true
  when: >
        base_force_apt_update is defined and
        base_force_apt_update

- name: debian | running apt-get dist-upgrade
  apt:
    upgrade: dist
  become: true
  when:
    base_debian_dist_upgrade

- name: debian | running apt-get upgrade
  apt:
    upgrade: safe
  become: true
  when:
    base_debian_upgrade

- name: debian | installing base packages
  apt:
    name: "{{ item }}"
    state: "present"
  become: true
  with_items: '{{ base_debian_packages }}'
...  
