---
- name: Set ssh keys for admin users from files
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ lookup('file', item.ssh_key) }}"
    exclusive: yes
  with_items: "{{ users }}"
  when: "item.ssh_key is defined and item.name in admin_users"
...  
